#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

fpath=(path/to/zsh-completions/src $fpath)

# Pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ -s "${ZDOTDIR:-$HOME}/google-cloud-sdk/path.zsh.inc" ]]; then
  # The next line updates PATH for the Google Cloud SDK.
  source "${ZDOTDIR:-$HOME}/google-cloud-sdk/path.zsh.inc"

  # The next line enables shell command completion for gcloud.
  source "${ZDOTDIR:-$HOME}/google-cloud-sdk/completion.zsh.inc"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.nodebrew/current/bin" ]]; then
  export PATH="${ZDOTDIR:-$HOME}/.nodebrew/current/bin:${PATH}"
fi

# For iTerm2
function chpwd() { ls; echo -ne "\033]0;$(pwd | rev | awk -F \/ '{print "/"$1"/"$2}'| rev)\007"}
chpwd

export EDITOR=vi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/tama/.nodebrew/node/v6.9.1/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/tama/.nodebrew/node/v6.9.1/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/tama/.nodebrew/node/v6.9.1/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/tama/.nodebrew/node/v6.9.1/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
